# Generated by Django 5.1.6 on 2025-02-18 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=10)),
                ('birth_date', models.DateField()),
                ('height_feet', models.IntegerField(blank=True, null=True)),
                ('height_inches', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField()),
                ('throws', models.CharField(max_length=1)),
                ('bats', models.CharField(max_length=1)),
                ('position', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BattingStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('plate_appearances', models.IntegerField()),
                ('at_bats', models.IntegerField()),
                ('runs', models.IntegerField()),
                ('hits', models.IntegerField()),
                ('doubles', models.IntegerField()),
                ('triples', models.IntegerField()),
                ('home_runs', models.IntegerField()),
                ('walks', models.IntegerField()),
                ('strikeouts', models.IntegerField()),
                ('stolen_bases', models.IntegerField()),
                ('caught_stealing', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_stats', to='players.player')),
            ],
        ),
    ]
