# Generated by Django 5.1.6 on 2025-02-21 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_alter_player_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battingstat',
            name='caught_stealing',
        ),
        migrations.RemoveField(
            model_name='battingstat',
            name='doubles',
        ),
        migrations.RemoveField(
            model_name='battingstat',
            name='plate_appearances',
        ),
        migrations.RemoveField(
            model_name='battingstat',
            name='runs',
        ),
        migrations.RemoveField(
            model_name='battingstat',
            name='strikeouts',
        ),
        migrations.RemoveField(
            model_name='battingstat',
            name='triples',
        ),
        migrations.RemoveField(
            model_name='battingstat',
            name='walks',
        ),
        migrations.RemoveField(
            model_name='player',
            name='height_inches',
        ),
    ]
