# Generated by Django 5.1.6 on 2025-02-23 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_rename_position_player_primary_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='primary_position',
            new_name='position',
        ),
    ]
