# Generated by Django 5.1.6 on 2025-02-23 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_rename_primary_position_player_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='first_name',
            new_name='name_first',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='last_name',
            new_name='name_last',
        ),
        migrations.RemoveField(
            model_name='player',
            name='position',
        ),
        migrations.AddField(
            model_name='battingstat',
            name='bases_on_balls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battingstat',
            name='caught_stealing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battingstat',
            name='doubles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battingstat',
            name='games',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battingstat',
            name='games_started',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battingstat',
            name='league',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='battingstat',
            name='org_abbreviation',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='battingstat',
            name='plate_appearances',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battingstat',
            name='runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battingstat',
            name='sacrifice_flies',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battingstat',
            name='sacrifices',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battingstat',
            name='strikeouts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battingstat',
            name='triples',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='height_inches',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='name_use',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='primary_position',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='battingstat',
            name='at_bats',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='battingstat',
            name='hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='battingstat',
            name='home_runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='battingstat',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting', to='players.player'),
        ),
        migrations.AlterField(
            model_name='battingstat',
            name='stolen_bases',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='bats',
            field=models.CharField(choices=[('L', 'Left'), ('R', 'Right'), ('S', 'Switch')], max_length=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='throws',
            field=models.CharField(choices=[('L', 'Left'), ('R', 'Right')], max_length=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PitchingStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('league', models.CharField(blank=True, max_length=10, null=True)),
                ('org_abbreviation', models.CharField(default='', max_length=10)),
                ('games', models.IntegerField(default=0)),
                ('games_started', models.IntegerField(default=0)),
                ('complete_games', models.IntegerField(default=0)),
                ('games_finished', models.IntegerField(default=0)),
                ('innings_pitched', models.FloatField(default=0.0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('saves', models.IntegerField(default=0)),
                ('total_batters_faced', models.IntegerField(default=0)),
                ('at_bats', models.IntegerField(default=0)),
                ('hits', models.IntegerField(default=0)),
                ('doubles', models.IntegerField(default=0)),
                ('triples', models.IntegerField(default=0)),
                ('home_runs', models.IntegerField(default=0)),
                ('bases_on_balls', models.IntegerField(default=0)),
                ('strikeouts', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitching', to='players.player')),
            ],
        ),
    ]
