# Generated by Django 5.1.6 on 2025-02-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_rename_first_name_player_name_first_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='primary_position',
            field=models.CharField(max_length=2),
        ),
    ]
