# Generated by Django 5.1.6 on 2025-02-23 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_alter_player_primary_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='primary_position',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
